### ISSUE TITLE
platform=win32 arch=ia32

### ISSUE THREAD

**Issue by dagouzhi** [SnosMe/uiohook-napi#11]
No native build was found for platform=win32 arch=ia32 runtime=electron abi=103 uv=1 libc=glibc node=16.13.2 electron=18.2.3

**Comment by dagouzhi** [comment]
event.preventDefault Whether it is available ？

**Comment by SnosMe** [comment]
I don't want to add binaries for legacy architecture.

If by preventing you mean https://github.com/kwhat/libuiohook/issues/57 it's not possible because events are delivered to js asynchronously.
