### ISSUE TITLE
MacOS / Linux builds

### ISSUE THREAD

**Issue by txj-xyz** [SnosMe/uiohook-napi#12]
DO we have instructions for building this for macos?

**Comment by SnosMe** [comment]
It ships with prebuilt napi module #8 , you don't need to do anything.

https://unpkg.com/browse/uiohook-napi@1.1.0/prebuilds/

**Comment by txj-xyz** [comment]
Re-opening this, this does not currently work on my Macbook Pro 2019 model. i9 16GB RAM

![](https://l.txj-dev.xyz/1TNrY)

**Comment by txj-xyz** [comment]
![](https://l.txj-dev.xyz/NnMyX)

**Comment by txj-xyz** [comment]
I'm not sure if there is something I'm doing incorrectly or not, but it does not work out of the box.

**Comment by txj-xyz** [comment]
@SnosMe

**Comment by SnosMe** [comment]
I don't own Mac and can't test, help.

If demos in https://github.com/kwhat/libuiohook/ work for you, then it's some issue here indeed. If so, we'll need contribution from someone.

**Comment by txj-xyz** [comment]
The demos do in fact work, I own a mac as well, I'm fully willing to give you access to it with me on perhaps Discord or some sort of communication platform.

A buddy of mine and myself are working on a project and we are at a standstill since we both do not know C and this library is the only working one out there, I'm willing to offer a payment as well for your services @SnosMe

**Comment by V01D-NULL** [comment]
@SnosMe Run MacOS in qemu, there should be some explanation for setting that up online.
I think it was a Github repo and a shell script or two :thinking:

**Comment by txj-xyz** [comment]
I do have a mac that you can test on as well

**Comment by SnosMe** [comment]
Can you test latest release

**Comment by txj-xyz** [comment]
It appears to be working now, we are still in development however all signs point to working.

**Comment by SnosMe** [comment]
@txj-xyz this library is just a wrapper, submit bugs to https://github.com/kwhat/libuiohook/

**Comment by txj-xyz** [comment]
Once again, modifiers work fine on `libuiohook`, I'll talk to them..
