### ISSUE TITLE
Anyway to get multikey input?

### ISSUE THREAD

**Issue by NightWarrior** [SnosMe/uiohook-napi#17]
Trying to send inputs to an Arduino board (remote car project with WASD keys) via bluetooth and using `serialport` library for that. I need to be able to detect multiple keys being pressed at once. E.g. `WS` pressed together. I assume an event should return something like an array of the inputs returned together that occurred at that time.

**Comment by SnosMe** [comment]
You should listen to keydown keyup events, have time window what you treat as "pressed at once" and act how you want when such combination happens.
It's what it's, when you are interested in combinations without Ctrl, Alt, it becomes harder.

> remote car project with WASD keys

take inspiration for input system implementation from game engines.
