### ISSUE TITLE
`mousemove` event not triggered when mouse is dragging

### ISSUE THREAD

**Issue by apolkingg8** [SnosMe/uiohook-napi#18]
As the title, `mousemove` event is not triggered when the mouse is dragging. Is this an expected behavior?

OS: Win10
Electron: 18.3.3
lib: 1.3.0

**Comment by SnosMe** [comment]
It's indeed not triggered

https://github.com/SnosMe/uiohook-napi/blob/b20d483aea29ac08c81ee9354e63fd34549507b0/src/lib/uiohook_worker.c#L72-L77

I want to review that part and make sure it aligns with how Web events work.

**Comment by apolkingg8** [comment]
I created a simple test. In the web environment, the `mousemove` event will be triggered when the mouse is dragging. You can try it here: https://jsfiddle.net/apolkingg8/oh46Ldzf/6/
