### ISSUE TITLE
Event timestamp

### ISSUE THREAD

**Issue by pie6k** [SnosMe/uiohook-napi#20]
I need to record mouse movement with high precision in terms of "when" mouse movement occured

use case - rendering smooth cursor movement over screen recording video. This means even slight screen-recording-video<>mouse-data time mismatch is clearly visible

Seems that events triggered by the lib do not include time when event occurred. Eg `event.timestamp`

I can of course include Date.now in my event handler, but it will be date at the moment when I handle the event, not the time when event actually occured (eg system picked mouse move). As JS is single threaded - delay between event and my code handling it might vary a lot. (In my case more than 1/60s delay can already "ruin" it)

Do you think it is possible to include such information or do you have some tips how can I captures timestamp of mouse movements as precisely as possible?

**Comment by SnosMe** [comment]
I have not checked if this is in consistent units on all platforms.
If it is not, we should report bug in the original repository.

**Comment by liamcmitchell** [comment]
It doesn't look like it's consistent.

LLM summary:

**Windows**
event.time is kbhook->time from the low-level keyboard hook struct.
This is a millisecond tick value (not Unix epoch), historically tied to the system tick/message time and it can wrap.

**macOS**
event.time is CGEventGetTimestamp, which is a high-resolution monotonic timestamp in nanoseconds.

**X11**
event.time is server_time from XRecord, which follows X server time semantics (millisecond-style server timestamp, different origin from both Windows and macOS).
