### ISSUE TITLE
arm64 arch not work 

### ISSUE THREAD

**Issue by dominic2013** [SnosMe/uiohook-napi#27]
[Uploading uiohook_napi.zip…]()
when i use this on arm64 it not work,i compile it on the arm64 machine, use this file put it in  node_modules/uiohook-napi/build/Release/uiohook_napi.node

**Comment by lmk123** [comment]
You don't need to compile one yourself.

When you install uiohook-napi, npm (and yarn) will automatically compile one for you and put it under a specific directory.

Here's a screenshot on my m1 arm64:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/5035625/209424484-0b2258fa-05ad-44df-8786-0281694c1b58.png">

**Comment by lmk123** [comment]
It is working fine in my computer.

If it doesn't work properly in your computer, you can provide us with the details of the error and we can confirm what the problem is.

**Comment by SnosMe** [comment]
I don't know what you are talking about. All releases come with prebuilt native node modules.
https://unpkg.com/browse/uiohook-napi@1.5.0/prebuilds/
