### ISSUE TITLE
Add the function of displaying mouse status

### ISSUE THREAD

**Issue by windyy0** [SnosMe/uiohook-napi#31]
thanks for a great lib.
Is it possible to add a display of the mouse state to the interface UiohookMouseEvent? For example, normal select, text select, unavailable, etc.
Just this mouse state, as shown in the picture.
![image](https://github.com/SnosMe/uiohook-napi/assets/44571034/9ec427f7-b99a-4aeb-a834-b880ab78d6a8)

**Comment by SnosMe** [comment]
The library https://github.com/kwhat/libuiohook/blob/1.2/include/uiohook.h
doesn't have this information, so no.
