### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by wan54** [SnosMe/uiohook-napi#38]
Is touch event planned to be supported anytime soon?

**Comment by SnosMe** [comment]
Is it something that upstream libuiohook has?

**Comment by wan54** [comment]
Not seen anywhere in https://github.com/kwhat/libuiohook/blob/1.2/src/windows/input_hook.c

Also confirmed by the owner https://github.com/kwhat/libuiohook/issues/62

From my recent testing with electron-based app, tapping on web contents will not trigger the `input` event. The event gets triggered when tapping on any native components: button, text input, window title bar, etc.

Closing since the upstream lib does not support it yet.

Thanks for making this binding.
