### ISSUE TITLE
request to update libUIOHook

### ISSUE THREAD

**Issue by marcelblum** [SnosMe/uiohook-napi#39]
Hello @SnosMe, as https://github.com/kwhat/libuiohook/pull/184 has now been merged into libUIOHook 1.2 branch, can you please update the libUIOHook build used here? That will fix the macOS `CGEventTap timeout!` bug that uiohook-napi inherited from libuiohook. And it removes the need for the https://github.com/SnosMe/uiohook-napi/pull/37 patch. Thanks to @hsource.

**Comment by nsharma1396** [comment]
@SnosMe any expected timeline on when this can be merged? I also have a macOS app that is facing this issue so an expected timeline can help
Thanks for the amazing and helpful work on this project though!
I can help with raising a PR for the fix but am not aware of the complete changes that will be needed to fix this issue.

**Comment by SnosMe** [comment]
sry for delay, released

**Comment by marcelblum** [comment]
thank you!
