### ISSUE TITLE
The Enter key is getting reported incorrectly on Windows

### ISSUE THREAD

**Issue by NoahAndrews** [SnosMe/uiohook-napi#45]
Enter on my Windows computer is reported with code `0xE1C` (NumpadEnter, see #44) instead of `28`.

I was going to submit this as a bug report to uiohook directly, but I see we're patching the library, and it's plausible that could have introduced this bug.

**Comment by ItsHarper** [comment]
@SnosMe It looks like you fixed this in 8858fa9229f9abdecf42ce227d75d00fb341ad2a, right? (it does seem fixed now)

**Comment by ItsHarper** [comment]
Ah, and then it was more properly fixed in 7fe4825eed86ef4b9e8226c0b2600031f6b8408e. I'm going to go ahead and close this, feel free to reopen if I misunderstood.
