### ISSUE TITLE
Support macOS arm64

### ISSUE THREAD

**Issue by lmk123** [SnosMe/uiohook-napi#8]
When used on a Macbook M1, the following error is reported:

```
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=103 uv=1 armv=8 libc=glibc node=16.13.2 electron=18.2.0 webpack=true
```

I hope you can provide the prebuild for macOS arm64, thanks.

**Comment by lmk123** [comment]
I have confirmed that uihook-napi@1.1.0 works fine with macOS arm64.

Thank you for your work.

**Comment by melMass** [comment]
@lmk123 Have you done anything special?

I'm still getting `Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=103 uv=1 armv=8 libc=glibc node=16.13.2 electron=18.2.3 webpack=true`

**Comment by lmk123** [comment]
@melMass try add this in your webpack config:

```js
externals: {
  'uiohook-napi': 'commonjs uiohook-napi'
},
```

**Comment by melMass** [comment]
Yes!! Thanks a lot @lmk123

**Comment by ondoki** [comment]
I still have this problem even though adding it to externals : `const configuration: webpack.Configuration = {
  externals: [
    ...Object.keys(
      externals || {
        'uiohook-napi': 'commonjs uiohook-napi',
      }
    ),
  ],`

...

**Comment by sh4hids** [comment]
If anyone using [vite](https://github.com/vitejs/vite) and having difficulties making `uiohook-nap` work, you can add it to `rollupOptions` in your `vite.config.js` like below:

```js
...
...
    rollupOptions: {
      external: [
        'electron',
        'electron-devtools-installer',
        'uiohook-napi',
        ...builtinModules.flatMap((p) => [p, `node:${p}`]),
      ],
      output: {
        entryFileNames: '[name].cjs',
      },
    },
...
...
```
